sudo: required
service:
  - docker
before_install:
  - docker build -t tomehta/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true tomehta/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-260108715116"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: AWS_SECRET_KEY
